version: 1
name: ocean-node-service
description: Ocean Protocol Node for AI Real Estate Data Broker

services:
  ocean-node:
    image: oceanprotocol/ocean-node:latest
    ports:
      - "8000:8000"
      - "9000:9000"
      - "9001:9001"
    environment:
      # Ocean Node Configuration
      PRIVATE_KEY: "${PRIVATE_KEY:-YOUR_PRIVATE_KEY_HERE}"
      
      # Network Configuration
      RPCS: '{"1":{"rpc":"https://ethereum-rpc.publicnode.com","fallbackRPCs":["https://rpc.ankr.com/eth","https://1rpc.io/eth","https://eth.api.onfinality.io/public"],"chainId":1,"network":"mainnet","chunkSize":100},"10":{"rpc":"https://mainnet.optimism.io","fallbackRPCs":["https://optimism-mainnet.public.blastapi.io","https://rpc.ankr.com/optimism","https://optimism-rpc.publicnode.com"],"chainId":10,"network":"optimism","chunkSize":100},"137":{"rpc":"https://polygon-rpc.com/","fallbackRPCs":["https://polygon-mainnet.public.blastapi.io","https://1rpc.io/matic","https://rpc.ankr.com/polygon"],"chainId":137,"network":"polygon","chunkSize":100},"11155111":{"rpc":"https://eth-sepolia.public.blastapi.io","fallbackRPCs":["https://1rpc.io/sepolia","https://eth-sepolia.g.alchemy.com/v2/demo"],"chainId":11155111,"network":"sepolia","chunkSize":100}}'
      
      # Database Configuration
      DB_URL: "http://typesense:8108/?apiKey=xyz"
      
      # Gateway Configuration
      IPFS_GATEWAY: "https://ipfs.io/"
      ARWEAVE_GATEWAY: "https://arweave.net/"
      
      # Service Configuration
      INTERFACES: '["HTTP","P2P"]'
      CONTROL_PANEL: "true"
      
      # HTTP API Configuration
      HTTP_API_PORT: "8000"
      
      # P2P Configuration
      P2P_ENABLE_IPV4: "true"
      P2P_ENABLE_IPV6: "false"
      P2P_ipV4BindAddress: "0.0.0.0"
      P2P_ipV4BindTcpPort: "9000"
      P2P_ipV4BindWsPort: "9001"
      P2P_ipV6BindAddress: "::"
      P2P_ipV6BindTcpPort: "9002"
      P2P_ipV6BindWsPort: "9003"
      
      # Compute Environment Configuration
      DOCKER_COMPUTE_ENVIRONMENTS: '[{"socketPath":"/var/run/docker.sock","resources":[{"id":"disk","total":1000000000}],"storageExpiry":604800,"maxJobDuration":36000,"fees":{"1":[{"feeToken":"0x123","prices":[{"id":"cpu","price":1}]}]},"free":{"maxJobDuration":360000,"maxJobs":3,"resources":[{"id":"cpu","max":1},{"id":"ram","max":1000000000},{"id":"disk","max":1000000000}]}}]'
      
      # Admin Configuration
      ALLOWED_ADMINS: '["${WALLET_ADDRESS:-YOUR_WALLET_ADDRESS_HERE}"]'
      
      # Free C2D Configuration
      ALLOW_FREE: "true"
      FREE_CALLS: "1000000"
      
    volumes:
      - node-sqlite:/usr/src/app/databases
    depends_on:
      - typesense
      
  typesense:
    image: typesense/typesense:26.0
    ports:
      - "8108:8108"
    volumes:
      - typesense-data:/data
    command: '--data-dir /data --api-key=xyz'
    
volumes:
  typesense-data:
  node-sqlite: 